spring:
  session:
    store-type: redis
    redis:
      namespace: cn.mariojd.session.redis
    timeout: 30s
  redis:
    url: redis://wnZUVQxP8FKL04FMqg9wb4yNMHO3pA*G@192.168.1.165:6379
    timeout: 5s
    database: 12
