spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  redis:
    host: localhost
  cache:
    # 非必须，但如果配置了需补充相应的依赖
    #type: redis
    redis:
      # 过期时间5秒，单位：毫秒
      time-to-live: 5000
      key-prefix: cn.mariojd.cache.
      cache-null-values: false
