spring:
  datasource:
    url: jdbc:mysql://192.168.1.165:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: winall
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update