server:
  port: 19999

spring:
  redis:
    host: localhost
    port: 12379
    database: 9
    password: redis6379
    jedis:
      pool:
        min-idle: 5
        max-idle: 20
        max-active: 20
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    url: jdbc:postgresql://127.0.0.1:12432/douban
    username: douban
    password: douban
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false