# appid 是应用的身份信息，需后台设定
app:
  id: 2019
# 一般指向 config service 服务地址
apollo:
  meta: http://localhost:8080

# 动态调整日志级别
logging:
  level:
    cn.mariojd.config.apollo: info

# 动态切换数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: root
    password: root
  jpa:
    open-in-view: false

server:
  port: 18080

